-- CREATE TYPE IF NOT EXISTS ESTADO_TURMA AS ENUM('ativo', 'encerrado', 'cancelado');
-- CREATE TYPE IF NOT EXISTS TIPO_AVALIACAO AS ENUM('prova', 'trabalho');
-- CREATE TYPE IF NOT EXISTS TIPO_ESTRUTURA AS ENUM('anfiteatro', 'laboratorio', 'sala_comum');
-- CREATE TYPE IF NOT EXISTS TIPO_LOUSA AS ENUM('branca', 'preta', 'digital');
-- CREATE TYPE IF NOT EXISTS FORMATO_MATERIAL AS ENUM('pdf', 'video', 'audio', 'livro');
-- CREATE TYPE IF NOT EXISTS REGIME_CURSO AS ENUM('semestre', 'anual');
-- CREATE TYPE IF NOT EXISTS ESTADO_PROJETO AS ENUM('planejado', 'em_andamento', 'finalizado');


CREATE TABLE IF NOT EXISTS CURSO (
	ID SERIAL PRIMARY KEY,
	NOME VARCHAR(60) UNIQUE NOT NULL,
	ID_COORDENADOR INTEGER NOT NULL,
	REGIME REGIME_CURSO NOT NULL,
	DURACAO INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS  PROFESSOR (
	ID SERIAL PRIMARY KEY,
	NOME VARCHAR(60) NOT NULL,
	AREA_PROFESSOR VARCHAR(60) NOT NULL,
	ID_CURSO INTEGER,
	CONTATO VARCHAR(60),
	FOREIGN KEY (ID_CURSO) REFERENCES CURSO (ID)
);

-- ALTER TABLE CURSO
-- ADD CONSTRAINT FK_ID_COORDENADOR FOREIGN KEY (ID_COORDENADOR) REFERENCES PROFESSOR (ID);

CREATE TABLE IF NOT EXISTS DISCIPLINA (
	NUMERO_DISCIPLINA SERIAL NOT NULL,
	AREA_DISCIPLINA VARCHAR(60) NOT NULL CHECK (LENGTH(AREA_DISCIPLINA) >= 2),
	ID VARCHAR(20) GENERATED ALWAYS AS (
		SUBSTRING(
			AREA_DISCIPLINA
			FROM
				1 FOR 2
		) || NUMERO_DISCIPLINA::TEXT
	) STORED,
	NOME VARCHAR(60) NOT NULL CHECK (NOME <> ''),
	CARGA_HORARIA INTEGER NOT NULL,
	EMENTA TEXT NOT NULL CHECK (EMENTA <> ''),
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS TURMA (
	ID_DISCIPLINA VARCHAR(20) NOT NULL,
	ID_CURSO INTEGER NOT NULL,
	nome_curso VARCHAR(60) NOT NULL, 
	numero_disciplina INTEGER not null, 
	ID VARCHAR(20) PRIMARY KEY GENERATED ALWAYS AS (
		SUBSTRING(
			NOME_CURSO
			FROM 
				1 FOR 2
		) || NUMERO_DISCIPLINA::TEXT
	) STORED,
	NOME VARCHAR(60) NOT NULL CHECK (NOME <> ''),
	SEMESTRE INTEGER NOT NULL,
	CAP_MAXIMA INTEGER NOT NULL,
	ESTADO ESTADO_TURMA NOT NULL,
	FOREIGN KEY (ID_CURSO) REFERENCES CURSO (ID),
	FOREIGN KEY (ID_DISCIPLINA) REFERENCES DISCIPLINA (ID)
	-- PRIMARY KEY (ID)
);

CREATE OR REPLACE FUNCTION sync_nome_curso_with_turma()
RETURNS TRIGGER AS $$
BEGIN
    -- Update 'nome_curso' em TURMA quando CURSO realiza update
    UPDATE TURMA
    SET nome_curso = NEW.NOME
    WHERE TURMA.ID_CURSO = NEW.ID;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION sync_numero_disciplina_with_turma()
RETURNS TRIGGER AS $$
BEGIN
    -- Update 'numero_disciplina' em TURMA quando DISCIPLINA realiza update
    UPDATE TURMA
    SET numero_disciplina = NEW.NUMERO_DISCIPLINA
    WHERE TURMA.ID_DISCIPLINA = NEW.ID;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_sync_nome_curso_with_turma
AFTER UPDATE OF NOME
ON CURSO
FOR EACH ROW
EXECUTE FUNCTION sync_nome_curso_with_turma();

CREATE TRIGGER trg_sync_numero_disciplina_with_turma
AFTER UPDATE OF NUMERO_DISCIPLINA
ON DISCIPLINA
FOR EACH ROW
EXECUTE FUNCTION sync_numero_disciplina_with_turma();



CREATE TABLE IF NOT EXISTS ALUNO (
	ID SERIAL PRIMARY KEY,
	MATRICULA CHAR(6) UNIQUE NOT NULL CHECK (MATRICULA ~ '^[0-9]{6}$'),
	NOME VARCHAR(60) NOT NULL CHECK (NOME <> ''),
	ID_CURSO INTEGER NOT NULL,
	NASCIMENTO DATE NOT NULL,
	ENTRADA INTEGER NOT NULL,
	CONCLUSAO INTEGER NOT NULL,
	CHECK (ENTRADA <= CONCLUSAO),
	FOREIGN KEY (ID_CURSO) REFERENCES CURSO (ID)
);

CREATE TABLE IF NOT EXISTS AVALIACAO (
	ID SERIAL PRIMARY KEY,
	TIPO TIPO_AVALIACAO NOT NULL,
	DATA_APLICACAO TIMESTAMP NOT NULL,
	PESO INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS NOTA (
	ID SERIAL PRIMARY KEY,
	ID_AVALIACAO INTEGER NOT NULL,
	VALOR REAL NOT NULL CHECK (
		VALOR >= 0
		AND VALOR <= 10
	),
	ID_ALUNO INTEGER NOT NULL,
	FOREIGN KEY (ID_AVALIACAO) REFERENCES AVALIACAO (ID),
	FOREIGN KEY (ID_ALUNO) REFERENCES ALUNO (ID)
);

CREATE TABLE IF NOT EXISTS SALA_DE_AULA (
	ID SERIAL PRIMARY KEY,
	TIPO_ESTRUTURA TIPO_ESTRUTURA NOT NULL,
	TIPO_LOUSA TIPO_LOUSA NOT NULL,
	CAPACIDADE INTEGER NOT NULL,
	LOCALIZACAO VARCHAR(255) NOT NULL CHECK (LOCALIZACAO <> '')
);

CREATE TABLE IF NOT EXISTS MATERIAL_DIDATICO (
	ID SERIAL PRIMARY KEY,
	TITULO VARCHAR(60) NOT NULL CHECK (TITULO <> ''),
	DESCRICAO VARCHAR(255) NOT NULL CHECK (DESCRICAO <> ''),
	FORMATO FORMATO_MATERIAL NOT NULL
);

-- TRIGGER para orc disponivel
CREATE TABLE IF NOT EXISTS PROJETO_PESQUISA (
	ID SERIAL PRIMARY KEY,
	TITULO VARCHAR(60) NOT NULL CHECK (TITULO <> ''),
	ID_COORDENADOR INTEGER NOT NULL,
	AREA VARCHAR(60) NOT NULL CHECK (AREA <> ''),
	DESCRICAO VARCHAR(255) NOT NULL CHECK (DESCRICAO <> ''),
	ORC_PLANEJADO REAL NOT NULL,
	ORC_REALIZADO REAL,
	ORC_DISPONIVEL REAL,
	ESTADO ESTADO_PROJETO NOT NULL,
	FOREIGN KEY (ID_COORDENADOR) REFERENCES PROFESSOR (ID),
	CHECK (ORC_REALIZADO IS NULL OR ORC_REALIZADO <= ORC_PLANEJADO)
);

-- Função de calculo do orc_disponivel na tablea PROJETO_PESQUISA
CREATE OR REPLACE FUNCTION calculate_orc_disponivel()
RETURNS TRIGGER AS $$
BEGIN
    -- Calcula ORC_DISPONIVEL como ORC_PLANEJADO - ORC_REALIZADO
    NEW.ORC_DISPONIVEL := NEW.ORC_PLANEJADO - COALESCE(NEW.ORC_REALIZADO, 0);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_calculate_orc_disponivel
BEFORE INSERT OR UPDATE OF ORC_REALIZADO ON PROJETO_PESQUISA
FOR EACH ROW
EXECUTE FUNCTION calculate_orc_disponivel();


-- Relations
CREATE TABLE IF NOT EXISTS PROFESSOR_TURMA (
	ID SERIAL PRIMARY KEY,
	ID_PROFESSOR INTEGER NOT NULL,
	ID_TURMA VARCHAR(20) NOT NULL,
	FOREIGN KEY (ID_PROFESSOR) REFERENCES PROFESSOR (ID),
	FOREIGN KEY (ID_TURMA) REFERENCES TURMA (ID)
);

CREATE TABLE IF NOT EXISTS PROFESSOR_CURSO (
	ID_PROFESSOR INTEGER PRIMARY KEY,
	ID_CURSO INTEGER NOT NULL,
	FOREIGN KEY (ID_PROFESSOR) REFERENCES PROFESSOR (ID),
	FOREIGN KEY (ID_CURSO) REFERENCES CURSO (ID)
);

CREATE TABLE IF NOT EXISTS DISCIPLINA_MATERIAL (
	ID SERIAL PRIMARY KEY,
	ID_DISCIPLINA VARCHAR(20) NOT NULL,
	ID_MATERIAL INTEGER NOT NULL,
	OPCIONAL BOOLEAN NOT NULL,
	FOREIGN KEY (ID_DISCIPLINA) REFERENCES DISCIPLINA (ID),
	FOREIGN KEY (ID_MATERIAL) REFERENCES MATERIAL_DIDATICO (ID)
);

CREATE TABLE IF NOT EXISTS ALUNO_TURMA (
	ID SERIAL PRIMARY KEY,
	ID_ALUNO INTEGER NOT NULL,
	ID_TURMA VARCHAR(20) NOT NULL,
	FOREIGN KEY (ID_ALUNO) REFERENCES ALUNO (ID),
	FOREIGN KEY (ID_TURMA) REFERENCES TURMA (ID)
);

CREATE TABLE IF NOT EXISTS SALA_TURMA (
	ID_TURMA VARCHAR(20) PRIMARY KEY,
	ID_SALA INTEGER NOT NULL,
	FOREIGN KEY (ID_TURMA) REFERENCES TURMA (ID),
	FOREIGN KEY (ID_SALA) REFERENCES SALA_DE_AULA (ID)
);

CREATE TABLE IF NOT EXISTS AVALIACAO_TURMA (
	ID SERIAL PRIMARY KEY,
	ID_AVALIACAO INTEGER NOT NULL,
	ID_TURMA VARCHAR(20) NOT NULL,
	FOREIGN KEY (ID_AVALIACAO) REFERENCES AVALIACAO (ID),
	FOREIGN KEY (ID_TURMA) REFERENCES TURMA (ID)
);

CREATE TABLE IF NOT EXISTS AVALIACAO_NOTA (
	ID_NOTA INTEGER PRIMARY KEY,
	ID_AVALIACAO INTEGER NOT NULL,
	FOREIGN KEY (ID_NOTA) REFERENCES NOTA (ID),
	FOREIGN KEY (ID_AVALIACAO) REFERENCES AVALIACAO (ID)
);

CREATE TABLE IF NOT EXISTS MATERIAL_PROFESSOR (
	ID SERIAL PRIMARY KEY,
	ID_MATERIAL INTEGER NOT NULL,
	ID_PROFESSOR INTEGER NOT NULL,
	FOREIGN KEY (ID_MATERIAL) REFERENCES MATERIAL_DIDATICO (ID),
	FOREIGN KEY (ID_PROFESSOR) REFERENCES PROFESSOR (ID)
);

CREATE TABLE IF NOT EXISTS MATERIAL_TURMA (
	ID SERIAL PRIMARY KEY,
	ID_MATERIAL INTEGER NOT NULL,
	ID_TURMA VARCHAR(20) NOT NULL,
	FOREIGN KEY (ID_MATERIAL) REFERENCES MATERIAL_DIDATICO (ID),
	FOREIGN KEY (ID_TURMA) REFERENCES TURMA (ID)
);

CREATE TABLE IF NOT EXISTS PROFESSOR_PROJETO (
	ID SERIAL PRIMARY KEY,
	ID_PROFESSOR INTEGER NOT NULL,
	ID_PROJETO INTEGER NOT NULL,
	FUNCAO VARCHAR(60) NOT NULL CHECK (FUNCAO <> ''),
	FOREIGN KEY (ID_PROFESSOR) REFERENCES PROFESSOR (ID),
	FOREIGN KEY (ID_PROJETO) REFERENCES PROJETO_PESQUISA (ID),
	UNIQUE (ID_PROJETO, FUNCAO)
);

CREATE TABLE IF NOT EXISTS ALUNO_PROJETO (
	ID SERIAL PRIMARY KEY,
	ID_ALUNO INTEGER NOT NULL,
	ID_PROJETO INTEGER NOT NULL,
	FUNCAO VARCHAR(60) NOT NULL CHECK (FUNCAO <> ''),
	FOREIGN KEY (ID_ALUNO) REFERENCES ALUNO (ID),
	FOREIGN KEY (ID_PROJETO) REFERENCES PROJETO_PESQUISA (ID),
	UNIQUE (ID_PROJETO, FUNCAO)
);