CREATE TYPE ESTADO_TURMA AS ENUM('ativo', 'encerrado', 'cancelado');

CREATE TYPE TIPO_AVALIACAO AS ENUM('prova', 'trabalho');

CREATE TYPE TIPO_ESTRUTURA AS ENUM('anfiteatro', 'laboratorio', 'sala_comum');

CREATE TYPE TIPO_LOUSA AS ENUM('branca', 'preta', 'digital');

CREATE TYPE FORMATO_MATERIAL AS ENUM('pdf', 'video', 'audio', 'livro');

CREATE TYPE REGIME_CURSO AS ENUM('semestre', 'anual');

CREATE TYPE ESTADO_PROJETO AS ENUM('planejado', 'em_andamento', 'finalizado');

CREATE TABLE CURSO (
	ID SERIAL PRIMARY KEY,
	NOME VARCHAR(60) UNIQUE NOT NULL,
	ID_COORDENADOR INTEGER NOT NULL,
	REGIME REGIME_CURSO NOT NULL,
	DURACAO INTEGER NOT NULL
);

CREATE TABLE PROFESSOR (
	ID SERIAL PRIMARY KEY,
	NOME VARCHAR(60) NOT NULL,
	AREA_PROFESSOR VARCHAR(60) NOT NULL,
	ID_CURSO INTEGER,
	CONTATO VARCHAR(60),
	FOREIGN KEY (ID_CURSO) REFERENCES CURSO (ID)
);

ALTER TABLE CURSO
ADD CONSTRAINT FK_ID_COORDENADOR FOREIGN KEY (ID_COORDENADOR) REFERENCES PROFESSOR (ID);

CREATE TABLE DISCIPLINA (
	NUMERO_DISCIPLINA SERIAL NOT NULL,
	AREA_DISCIPLINA VARCHAR(60) NOT NULL CHECK (LENGTH(AREA_DISCIPLINA) >= 2),
	ID VARCHAR(20) GENERATED ALWAYS AS (
		SUBSTRING(
			AREA_DISCIPLINA
			FROM
				1 FOR 2
		) || NUMERO_DISCIPLINA::TEXT
	) STORED,
	NOME VARCHAR(60) NOT NULL CHECK (NOME <> ''),
	CARGA_HORARIA INTEGER NOT NULL,
	EMENTA TEXT NOT NULL CHECK (EMENTA <> ''),
	PRIMARY KEY (ID)
);

CREATE TABLE TURMA (
	ID_DISCIPLINA VARCHAR(20) NOT NULL,
	ID_CURSO INTEGER NOT NULL,
	ID VARCHAR(20) PRIMARY KEY,
	NOME VARCHAR(60) NOT NULL CHECK (NOME <> ''),
	SEMESTRE INTEGER NOT NULL,
	CAP_MAXIMA INTEGER NOT NULL,
	ESTADO ESTADO_TURMA NOT NULL,
	FOREIGN KEY (ID_CURSO) REFERENCES CURSO (ID),
	FOREIGN KEY (ID_DISCIPLINA) REFERENCES DISCIPLINA (ID)
	-- PRIMARY KEY (ID)
);

CREATE TABLE ALUNO (
	ID SERIAL PRIMARY KEY,
	MATRICULA CHAR(6) UNIQUE NOT NULL CHECK (MATRICULA ~ '^[0-9]{6}$'),
	NOME VARCHAR(60) NOT NULL CHECK (NOME <> ''),
	ID_CURSO INTEGER NOT NULL,
	NASCIMENTO DATE NOT NULL,
	ENTRADA INTEGER NOT NULL,
	CONCLUSAO INTEGER NOT NULL,
	CHECK (ENTRADA <= CONCLUSAO),
	FOREIGN KEY (ID_CURSO) REFERENCES CURSO (ID)
);

CREATE TABLE AVALIACAO (
	ID SERIAL PRIMARY KEY,
	TIPO TIPO_AVALIACAO NOT NULL,
	DATA_APLICACAO TIMESTAMP NOT NULL,
	PESO INTEGER NOT NULL
);

CREATE TABLE NOTA (
	ID SERIAL PRIMARY KEY,
	ID_AVALIACAO INTEGER NOT NULL,
	VALOR REAL NOT NULL CHECK (
		VALOR >= 0
		AND VALOR <= 10
	),
	ID_ALUNO INTEGER NOT NULL,
	FOREIGN KEY (ID_AVALIACAO) REFERENCES AVALIACAO (ID),
	FOREIGN KEY (ID_ALUNO) REFERENCES ALUNO (ID)
);

CREATE TABLE SALA_DE_AULA (
	ID SERIAL PRIMARY KEY,
	TIPO_ESTRUTURA TIPO_ESTRUTURA NOT NULL,
	TIPO_LOUSA TIPO_LOUSA NOT NULL,
	CAPACIDADE INTEGER NOT NULL,
	LOCALIZACAO VARCHAR(255) NOT NULL CHECK (LOCALIZACAO <> '')
);

CREATE TABLE MATERIAL_DIDATICO (
	ID SERIAL PRIMARY KEY,
	TITULO VARCHAR(60) NOT NULL CHECK (TITULO <> ''),
	DESCRICAO VARCHAR(255) NOT NULL CHECK (DESCRICAO <> ''),
	FORMATO FORMATO_MATERIAL NOT NULL
);

CREATE TABLE PROJETO_PESQUISA (
	ID SERIAL PRIMARY KEY,
	TITULO VARCHAR(60) NOT NULL CHECK (TITULO <> ''),
	ID_COORDENADOR INTEGER NOT NULL,
	AREA VARCHAR(60) NOT NULL CHECK (AREA <> ''),
	DESCRICAO VARCHAR(255) NOT NULL CHECK (DESCRICAO <> ''),
	ORC_PLANEJADO REAL NOT NULL,
	ORC_REALIZADO REAL,
	ORC_DISPONIVEL REAL,
	ESTADO ESTADO_PROJETO NOT NULL,
	FOREIGN KEY (ID_COORDENADOR) REFERENCES PROFESSOR (ID)
);

-- Relations
CREATE TABLE PROFESSOR_TURMA (
	ID SERIAL PRIMARY KEY,
	ID_PROFESSOR INTEGER NOT NULL,
	ID_TURMA VARCHAR(20) NOT NULL,
	FOREIGN KEY (ID_PROFESSOR) REFERENCES PROFESSOR (ID),
	FOREIGN KEY (ID_TURMA) REFERENCES TURMA (ID)
);

CREATE TABLE PROFESSOR_CURSO (
	ID_PROFESSOR INTEGER PRIMARY KEY,
	ID_CURSO INTEGER NOT NULL,
	FOREIGN KEY (ID_PROFESSOR) REFERENCES PROFESSOR (ID),
	FOREIGN KEY (ID_CURSO) REFERENCES CURSO (ID)
);

CREATE TABLE DISCIPLINA_MATERIAL (
	ID SERIAL PRIMARY KEY,
	ID_DISCIPLINA VARCHAR(20) NOT NULL,
	ID_MATERIAL INTEGER NOT NULL,
	OPCIONAL BOOLEAN NOT NULL,
	FOREIGN KEY (ID_DISCIPLINA) REFERENCES DISCIPLINA (ID),
	FOREIGN KEY (ID_MATERIAL) REFERENCES MATERIAL_DIDATICO (ID)
);

CREATE TABLE ALUNO_TURMA (
	ID SERIAL PRIMARY KEY,
	ID_ALUNO INTEGER NOT NULL,
	ID_TURMA VARCHAR(20) NOT NULL,
	FOREIGN KEY (ID_ALUNO) REFERENCES ALUNO (ID),
	FOREIGN KEY (ID_TURMA) REFERENCES TURMA (ID)
);

CREATE TABLE SALA_TURMA (
	ID_TURMA VARCHAR(20) PRIMARY KEY,
	ID_SALA INTEGER NOT NULL,
	FOREIGN KEY (ID_TURMA) REFERENCES TURMA (ID),
	FOREIGN KEY (ID_SALA) REFERENCES SALA_DE_AULA (ID)
);

CREATE TABLE AVALIACAO_TURMA (
	ID SERIAL PRIMARY KEY,
	ID_AVALIACAO INTEGER NOT NULL,
	ID_TURMA VARCHAR(20) NOT NULL,
	FOREIGN KEY (ID_AVALIACAO) REFERENCES AVALIACAO (ID),
	FOREIGN KEY (ID_TURMA) REFERENCES TURMA (ID)
);

CREATE TABLE AVALIACAO_NOTA (
	ID_NOTA INTEGER PRIMARY KEY,
	ID_AVALIACAO INTEGER NOT NULL,
	FOREIGN KEY (ID_NOTA) REFERENCES NOTA (ID),
	FOREIGN KEY (ID_AVALIACAO) REFERENCES AVALIACAO (ID)
);

CREATE TABLE MATERIAL_PROFESSOR (
	ID SERIAL PRIMARY KEY,
	ID_MATERIAL INTEGER NOT NULL,
	ID_PROFESSOR INTEGER NOT NULL,
	FOREIGN KEY (ID_MATERIAL) REFERENCES MATERIAL_DIDATICO (ID),
	FOREIGN KEY (ID_PROFESSOR) REFERENCES PROFESSOR (ID)
);

CREATE TABLE MATERIAL_TURMA (
	ID SERIAL PRIMARY KEY,
	ID_MATERIAL INTEGER NOT NULL,
	ID_TURMA VARCHAR(20) NOT NULL,
	FOREIGN KEY (ID_MATERIAL) REFERENCES MATERIAL_DIDATICO (ID),
	FOREIGN KEY (ID_TURMA) REFERENCES TURMA (ID)
);

CREATE TABLE PROFESSOR_PROJETO (
	ID SERIAL PRIMARY KEY,
	ID_PROFESSOR INTEGER NOT NULL,
	ID_PROJETO INTEGER NOT NULL,
	FUNCAO VARCHAR(60) NOT NULL CHECK (FUNCAO <> ''),
	FOREIGN KEY (ID_PROFESSOR) REFERENCES PROFESSOR (ID),
	FOREIGN KEY (ID_PROJETO) REFERENCES PROJETO_PESQUISA (ID),
	UNIQUE (ID_PROJETO, FUNCAO)
);

CREATE TABLE ALUNO_PROJETO (
	ID SERIAL PRIMARY KEY,
	ID_ALUNO INTEGER NOT NULL,
	ID_PROJETO INTEGER NOT NULL,
	FUNCAO VARCHAR(60) NOT NULL CHECK (FUNCAO <> ''),
	FOREIGN KEY (ID_ALUNO) REFERENCES ALUNO (ID),
	FOREIGN KEY (ID_PROJETO) REFERENCES PROJETO_PESQUISA (ID),
	UNIQUE (ID_PROJETO, FUNCAO)
);